branches:
  only: master

language: bash

services:
  - docker

matrix:
  fast_finish: true
  include:
    - env:
      - VERSION=7.2
      - ALIAS=latest
    - env:
      - VERSION=7.2
      - VARIANT=fpm
      - ALIAS=fpm
    - env:
      - VERSION=7.2
      - VARIANT=apache
      - ALIAS=apache
    - env:
      - VERSION=7.2
      - BASE=alpine
      - ALIAS=alpine
    - env:
      - VERSION=7.2
      - VARIANT=fpm
      - BASE=alpine
      - ALIAS=fpm-alpine
    - env:
      - VERSION=7.1
    - env:
      - VERSION=7.1
      - VARIANT=fpm
    - env:
      - VERSION=7.1
      - VARIANT=apache
    - env:
      - VERSION=7.1
      - BASE=alpine
    - env:
      - VERSION=7.1
      - VARIANT=fpm
      - BASE=alpine

script:
  - ./build

after_success:
  - docker images
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker push nexylan/php-dev; fi
